/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Doctor;

/**
 *
 * @author hotra
 */
public class doctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaientJPanel
     */
    Doctor doctor = new Doctor();
    public doctorJPanel(Doctor doctor) {
        initComponents();
        this.doctor = doctor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitle3 = new javax.swing.JLabel();
        lblDoctorSpecilty = new javax.swing.JLabel();
        lblDoctorLicenseNo = new javax.swing.JLabel();
        lblDoctorContactNo = new javax.swing.JLabel();
        lblDoctorName = new javax.swing.JLabel();
        lblDoctorOfficeAddress = new javax.swing.JLabel();
        lblDoctorCertifiedBoard = new javax.swing.JLabel();
        lblDoctorExperience = new javax.swing.JLabel();
        txtDoctorSpecialty = new javax.swing.JTextField();
        txtDoctorExperience = new javax.swing.JTextField();
        txtDoctorName = new javax.swing.JTextField();
        txtDoctorOfficeAddress = new javax.swing.JTextField();
        txtDoctorLicenseNo = new javax.swing.JTextField();
        txtDoctorCertifiedBoard = new javax.swing.JTextField();
        txtDoctorContactInfo = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        lblTitle3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle3.setText("Doctor Information");
        lblTitle3.setToolTipText("");

        lblDoctorSpecilty.setText("Specialty:");

        lblDoctorLicenseNo.setText("License No:");

        lblDoctorContactNo.setText("Contact Info:");

        lblDoctorName.setText("Name:");

        lblDoctorOfficeAddress.setText("Office Address:");

        lblDoctorCertifiedBoard.setText("Certified Board:");

        lblDoctorExperience.setText("Experience(Years):");

        txtDoctorSpecialty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorSpecialtyActionPerformed(evt);
            }
        });

        txtDoctorExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorExperienceActionPerformed(evt);
            }
        });

        txtDoctorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorNameActionPerformed(evt);
            }
        });

        txtDoctorOfficeAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorOfficeAddressActionPerformed(evt);
            }
        });

        txtDoctorLicenseNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorLicenseNoActionPerformed(evt);
            }
        });

        txtDoctorCertifiedBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorCertifiedBoardActionPerformed(evt);
            }
        });

        txtDoctorContactInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorContactInfoActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(lblTitle3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDoctorCertifiedBoard)
                                    .addComponent(lblDoctorContactNo))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDoctorContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDoctorCertifiedBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDoctorSpecilty)
                                    .addComponent(lblDoctorOfficeAddress)
                                    .addComponent(lblDoctorLicenseNo)
                                    .addComponent(lblDoctorName)
                                    .addComponent(lblDoctorExperience))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDoctorName)
                                    .addComponent(txtDoctorOfficeAddress)
                                    .addComponent(txtDoctorLicenseNo)
                                    .addComponent(txtDoctorSpecialty)
                                    .addComponent(txtDoctorExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(btnSave)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(lblTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorName)
                    .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorOfficeAddress)
                    .addComponent(txtDoctorOfficeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorLicenseNo)
                    .addComponent(txtDoctorLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorSpecilty)
                    .addComponent(txtDoctorSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorExperience)
                    .addComponent(txtDoctorExperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorCertifiedBoard)
                    .addComponent(txtDoctorCertifiedBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorContactNo)
                    .addComponent(txtDoctorContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(129, 129, 129))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDoctorSpecialtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorSpecialtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorSpecialtyActionPerformed

    private void txtDoctorExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorExperienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorExperienceActionPerformed

    private void txtDoctorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorNameActionPerformed

    private void txtDoctorOfficeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorOfficeAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorOfficeAddressActionPerformed

    private void txtDoctorLicenseNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorLicenseNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorLicenseNoActionPerformed

    private void txtDoctorCertifiedBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorCertifiedBoardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorCertifiedBoardActionPerformed

    private void txtDoctorContactInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorContactInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorContactInfoActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        

        // Doctor Info
        doctor.setCertifiedBoard(txtDoctorCertifiedBoard.getText());
        doctor.setContactInfo(txtDoctorContactInfo.getText());
        doctor.setExperience(txtDoctorExperience.getText());
        doctor.setSpecialty(txtDoctorSpecialty.getText());
        doctor.setLicenseNo(txtDoctorLicenseNo.getText());
        doctor.setOfficeAddress(txtDoctorOfficeAddress.getText());
        doctor.setName(txtDoctorName.getText());
                        
        JOptionPane.showMessageDialog(this, "Doctor details are saved");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDoctorCertifiedBoard;
    private javax.swing.JLabel lblDoctorContactNo;
    private javax.swing.JLabel lblDoctorExperience;
    private javax.swing.JLabel lblDoctorLicenseNo;
    private javax.swing.JLabel lblDoctorName;
    private javax.swing.JLabel lblDoctorOfficeAddress;
    private javax.swing.JLabel lblDoctorSpecilty;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JTextField txtDoctorCertifiedBoard;
    private javax.swing.JTextField txtDoctorContactInfo;
    private javax.swing.JTextField txtDoctorExperience;
    private javax.swing.JTextField txtDoctorLicenseNo;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtDoctorOfficeAddress;
    private javax.swing.JTextField txtDoctorSpecialty;
    // End of variables declaration//GEN-END:variables
}
