/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JPanel;
import model.Address;
import model.Doctor;
import model.Driver;
import model.Insurance;
import model.Patient;
import model.Person;
import model.VehicleRegistration;

/**
 *
 * @author hotra
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    Person person;
    Address address;
    Driver driver;
    VehicleRegistration vehicleRegistration;
    Patient patient;
    Insurance insurance;
    Doctor doctor;
    
    public MainJFrame() {
        initComponents();
        
        person = new Person();
        address = new Address();
        driver = new Driver();
        vehicleRegistration = new VehicleRegistration();
        patient = new Patient();
        insurance = new Insurance();
        doctor = new Doctor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        consolePanel = new javax.swing.JPanel();
        btnPerson = new javax.swing.JButton();
        btnDriver = new javax.swing.JButton();
        btnVehicleReg = new javax.swing.JButton();
        btnPatient = new javax.swing.JButton();
        btnDisReport = new javax.swing.JButton();
        btnAddress = new javax.swing.JButton();
        btnInsuranceCoverage = new javax.swing.JButton();
        btnDoctor = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        consolePanel.setPreferredSize(new java.awt.Dimension(254, 600));

        btnPerson.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPerson.setText("Person");
        btnPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonActionPerformed(evt);
            }
        });

        btnDriver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDriver.setText("Driver");
        btnDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDriverActionPerformed(evt);
            }
        });

        btnVehicleReg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVehicleReg.setText("Vehicle Registration");
        btnVehicleReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicleRegActionPerformed(evt);
            }
        });

        btnPatient.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPatient.setText("Patient");
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });

        btnDisReport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDisReport.setText("Display Report");
        btnDisReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDisReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisReportActionPerformed(evt);
            }
        });

        btnAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddress.setText("Address");
        btnAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddressActionPerformed(evt);
            }
        });

        btnInsuranceCoverage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInsuranceCoverage.setText("Insurance Coverage");
        btnInsuranceCoverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsuranceCoverageActionPerformed(evt);
            }
        });

        btnDoctor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDoctor.setText("Doctor");
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consolePanelLayout = new javax.swing.GroupLayout(consolePanel);
        consolePanel.setLayout(consolePanelLayout);
        consolePanelLayout.setHorizontalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolePanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnPerson, javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnDriver)
                            .addComponent(btnVehicleReg)
                            .addComponent(btnPatient)
                            .addComponent(btnDisReport, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsuranceCoverage)
                            .addComponent(btnDoctor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        consolePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDisReport, btnDriver, btnPatient, btnPerson, btnVehicleReg});

        consolePanelLayout.setVerticalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolePanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnPerson)
                .addGap(30, 30, 30)
                .addComponent(btnAddress)
                .addGap(30, 30, 30)
                .addComponent(btnDriver)
                .addGap(30, 30, 30)
                .addComponent(btnVehicleReg)
                .addGap(30, 30, 30)
                .addComponent(btnPatient)
                .addGap(30, 30, 30)
                .addComponent(btnInsuranceCoverage)
                .addGap(30, 30, 30)
                .addComponent(btnDoctor)
                .addGap(30, 30, 30)
                .addComponent(btnDisReport)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        consolePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDisReport, btnDriver, btnPatient, btnPerson, btnVehicleReg});

        splitPane.setLeftComponent(consolePanel);

        workArea.setPreferredSize(new java.awt.Dimension(600, 600));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(3);
        jTextArea1.setText("                       Welcome \nPlease Fill In All Details And Generate A \nFinal Report Using Display Report Button");
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleParent(workArea);

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAreaLayout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonActionPerformed
        // TODO add your handling code here:
        splitPane.setRightComponent(new JPanel());
        personJPanel personPanel = new personJPanel(person);
        splitPane.setRightComponent(personPanel);
    }//GEN-LAST:event_btnPersonActionPerformed

    private void btnDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDriverActionPerformed
        // TODO add your handling code here:
        driverJPanel driverPanel = new driverJPanel(driver);
        splitPane.setRightComponent(driverPanel);
    }//GEN-LAST:event_btnDriverActionPerformed

    private void btnVehicleRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicleRegActionPerformed
        // TODO add your handling code here:
        vehicleRegJPanel vehicleRegPanel = new vehicleRegJPanel(vehicleRegistration);
        splitPane.setRightComponent(vehicleRegPanel);
    }//GEN-LAST:event_btnVehicleRegActionPerformed

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        // TODO add your handling code here:
        patientJPanel patientPanel = new patientJPanel(patient);
        splitPane.setRightComponent(patientPanel);
    }//GEN-LAST:event_btnPatientActionPerformed

    private void btnDisReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisReportActionPerformed
        // TODO add your handling code here:
        
        disReportJPanel disReportPanel = new disReportJPanel(person, address, patient, doctor, insurance, driver, vehicleRegistration);
        splitPane.setRightComponent(disReportPanel);
    }//GEN-LAST:event_btnDisReportActionPerformed

    private void btnAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddressActionPerformed
        // TODO add your handling code here:
        addressJPanel addressPanel = new addressJPanel(address);
        splitPane.setRightComponent(addressPanel);
    }//GEN-LAST:event_btnAddressActionPerformed

    private void btnInsuranceCoverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsuranceCoverageActionPerformed
        // TODO add your handling code here:
        insuranceCoverageJPanel insuranceCoveragePanel = new insuranceCoverageJPanel(patient, insurance);
        splitPane.setRightComponent(insuranceCoveragePanel);
        
    }//GEN-LAST:event_btnInsuranceCoverageActionPerformed

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
        doctorJPanel doctorPanel = new doctorJPanel(doctor);
        splitPane.setRightComponent(doctorPanel);
    }//GEN-LAST:event_btnDoctorActionPerformed

    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddress;
    private javax.swing.JButton btnDisReport;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnDriver;
    private javax.swing.JButton btnInsuranceCoverage;
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton btnPerson;
    private javax.swing.JButton btnVehicleReg;
    private javax.swing.JPanel consolePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
