/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Patient;

/**
 *
 * @author hotra
 */
public class patientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaientJPanel
     */
    Patient patient = new Patient();
    public patientJPanel(Patient patient) {
        initComponents();
        this.patient = patient;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitle1 = new javax.swing.JLabel();
        lblPatientId = new javax.swing.JLabel();
        lblPatientPrimaryDoctor = new javax.swing.JLabel();
        lblPatientLastVisit = new javax.swing.JLabel();
        lblPatientAllergies = new javax.swing.JLabel();
        lblPatientOnMedication = new javax.swing.JLabel();
        lblPatentNextVisitDate = new javax.swing.JLabel();
        lblPatientHabits = new javax.swing.JLabel();
        txtPatientPrimaryDoctor = new javax.swing.JTextField();
        txtPatientLastVisitDate = new javax.swing.JTextField();
        txtPatientNextVisitDate = new javax.swing.JTextField();
        txtPatientId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jRadioButtonAllergiesYes = new javax.swing.JRadioButton();
        jRadioButtonAllergiesNo = new javax.swing.JRadioButton();
        jRadioButtonMedicationYes = new javax.swing.JRadioButton();
        jRadioButtonMedicationNo = new javax.swing.JRadioButton();
        jCheckBoxSmoking = new javax.swing.JCheckBox();
        jCheckBoxDrinking = new javax.swing.JCheckBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 181, 499, 17));

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Patient Information");
        lblTitle1.setToolTipText("");
        add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 131, -1, -1));

        lblPatientId.setText("Id:");
        add(lblPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 219, -1, -1));

        lblPatientPrimaryDoctor.setText("Primary Doctor:");
        add(lblPatientPrimaryDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 251, -1, -1));

        lblPatientLastVisit.setText("Last Visit Date:");
        add(lblPatientLastVisit, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 283, -1, -1));

        lblPatientAllergies.setText("Allergies:");
        add(lblPatientAllergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 348, -1, -1));

        lblPatientOnMedication.setText("On Medication:");
        add(lblPatientOnMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 374, -1, -1));

        lblPatentNextVisitDate.setText("Next Visit Date:");
        add(lblPatentNextVisitDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 317, -1, -1));

        lblPatientHabits.setText("Habits:");
        add(lblPatientHabits, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 400, 39, -1));

        txtPatientPrimaryDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientPrimaryDoctorActionPerformed(evt);
            }
        });
        add(txtPatientPrimaryDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 248, 191, -1));

        txtPatientLastVisitDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientLastVisitDateActionPerformed(evt);
            }
        });
        add(txtPatientLastVisitDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 280, 191, -1));

        txtPatientNextVisitDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNextVisitDateActionPerformed(evt);
            }
        });
        add(txtPatientNextVisitDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 314, 191, -1));

        txtPatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIdActionPerformed(evt);
            }
        });
        add(txtPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 216, 191, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 448, -1, -1));

        buttonGroup1.add(jRadioButtonAllergiesYes);
        jRadioButtonAllergiesYes.setText("Yes");
        add(jRadioButtonAllergiesYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 346, -1, -1));

        buttonGroup1.add(jRadioButtonAllergiesNo);
        jRadioButtonAllergiesNo.setText("No");
        jRadioButtonAllergiesNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAllergiesNoActionPerformed(evt);
            }
        });
        add(jRadioButtonAllergiesNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 346, -1, -1));

        buttonGroup2.add(jRadioButtonMedicationYes);
        jRadioButtonMedicationYes.setText("Yes");
        add(jRadioButtonMedicationYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 372, -1, -1));

        buttonGroup2.add(jRadioButtonMedicationNo);
        jRadioButtonMedicationNo.setText("No");
        jRadioButtonMedicationNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMedicationNoActionPerformed(evt);
            }
        });
        add(jRadioButtonMedicationNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 372, -1, -1));

        jCheckBoxSmoking.setText("Smoking");
        jCheckBoxSmoking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSmokingActionPerformed(evt);
            }
        });
        add(jCheckBoxSmoking, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 398, -1, -1));

        jCheckBoxDrinking.setText("Drinking");
        jCheckBoxDrinking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDrinkingActionPerformed(evt);
            }
        });
        add(jCheckBoxDrinking, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 398, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIdActionPerformed

    private void txtPatientPrimaryDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientPrimaryDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientPrimaryDoctorActionPerformed

    private void txtPatientLastVisitDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientLastVisitDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientLastVisitDateActionPerformed

    private void txtPatientNextVisitDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNextVisitDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNextVisitDateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        // Patient Info
        patient.setId(txtPatientId.getText());
        patient.setAllergies(jRadioButtonAllergiesYes.isSelected());
        patient.setOnMedication(jRadioButtonMedicationYes.isSelected());
        patient.setDrinking(jCheckBoxDrinking.isSelected());
        patient.setSmoking(jCheckBoxSmoking.isSelected());
        patient.setPrimaryDoctor(txtPatientPrimaryDoctor.getText());
        patient.setLastVisitDate(txtPatientLastVisitDate.getText());
        patient.setNextVisitDate(txtPatientNextVisitDate.getText());
                
        JOptionPane.showMessageDialog(this, "Patient details are saved");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jRadioButtonAllergiesNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAllergiesNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAllergiesNoActionPerformed

    private void jRadioButtonMedicationNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMedicationNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMedicationNoActionPerformed

    private void jCheckBoxSmokingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSmokingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSmokingActionPerformed

    private void jCheckBoxDrinkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDrinkingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxDrinkingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBoxDrinking;
    private javax.swing.JCheckBox jCheckBoxSmoking;
    private javax.swing.JRadioButton jRadioButtonAllergiesNo;
    private javax.swing.JRadioButton jRadioButtonAllergiesYes;
    private javax.swing.JRadioButton jRadioButtonMedicationNo;
    private javax.swing.JRadioButton jRadioButtonMedicationYes;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblPatentNextVisitDate;
    private javax.swing.JLabel lblPatientAllergies;
    private javax.swing.JLabel lblPatientHabits;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblPatientLastVisit;
    private javax.swing.JLabel lblPatientOnMedication;
    private javax.swing.JLabel lblPatientPrimaryDoctor;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPatientLastVisitDate;
    private javax.swing.JTextField txtPatientNextVisitDate;
    private javax.swing.JTextField txtPatientPrimaryDoctor;
    // End of variables declaration//GEN-END:variables
}
