/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author hotra
 */
public class personJPanel extends javax.swing.JPanel {

    /**
     * Creates new form personJPanel
     */
    
    Person person;
    
    public personJPanel(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblWebUrl = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblMaritalStatus = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtWebURL = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtMaritalStaus = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblProPic = new javax.swing.JLabel();
        btnPicUpload = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Personal Info");
        lblTitle.setToolTipText("");
        lblTitle.setRequestFocusEnabled(false);
        lblTitle.setVerifyInputWhenFocusTarget(false);
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 108, -1, -1));

        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFirstName.setText("First Name:");
        lblFirstName.setPreferredSize(null);
        add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 183, -1, -1));

        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastName.setText("Last Name:");
        lblLastName.setPreferredSize(null);
        add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 215, -1, -1));

        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSSN.setText("SSN:");
        lblSSN.setPreferredSize(null);
        add(lblSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 247, -1, -1));

        lblWebUrl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblWebUrl.setText("Website URL:");
        lblWebUrl.setPreferredSize(null);
        add(lblWebUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 279, -1, -1));

        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGender.setText("Gender:");
        lblGender.setPreferredSize(null);
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 340, -1, -1));

        lblMaritalStatus.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMaritalStatus.setText("Marital Status:");
        lblMaritalStatus.setPreferredSize(null);
        add(lblMaritalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 436, -1, -1));

        lblDob.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDob.setText("Date Of Birth:");
        lblDob.setPreferredSize(null);
        add(lblDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 372, -1, -1));

        lblWeight.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblWeight.setText("Weight:");
        add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 404, -1, -1));

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmail.setText("Email:");
        lblEmail.setPreferredSize(null);
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 311, -1, -1));

        txtFirstName.setToolTipText("");
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 180, 300, -1));

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 212, 300, -1));

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });
        add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 244, 300, -1));

        txtWebURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWebURLActionPerformed(evt);
            }
        });
        add(txtWebURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 276, 300, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 308, 300, -1));

        txtMaritalStaus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaritalStausActionPerformed(evt);
            }
        });
        add(txtMaritalStaus, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 433, 300, -1));

        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 337, 300, -1));

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });
        add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 369, 300, -1));

        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 401, 300, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 158, 504, 4));

        lblProPic.setText("Profile Picture:");
        add(lblProPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 465, -1, -1));

        btnPicUpload.setText("Upload File");
        btnPicUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPicUploadActionPerformed(evt);
            }
        });
        add(btnPicUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 462, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 502, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtWebURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWebURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWebURLActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtMaritalStausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaritalStausActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaritalStausActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void btnPicUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPicUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
                int result = fileChooser.showOpenDialog(null);
              
                if (result == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = fileChooser.getSelectedFile();
                    person.setProfilePicPath(selectedFile.getAbsolutePath());
                }
    }//GEN-LAST:event_btnPicUploadActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        person.setFirstName(txtFirstName.getText());
        person.setDob(txtDOB.getText());
        person.setEmail(txtEmail.getText());
        person.setGender(txtGender.getText());
        person.setLastName(txtLastName.getText());
        person.setMaritalStatus(txtMaritalStaus.getText());
        person.setSsn(txtSSN.getText());
        person.setWebUrl(txtWebURL.getText());
        person.setWeight(txtWeight.getText());

        JOptionPane.showMessageDialog(this, "Personal information is saved");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPicUpload;
    private javax.swing.JButton btnSave;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMaritalStatus;
    private javax.swing.JLabel lblProPic;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWebUrl;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMaritalStaus;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWebURL;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
